# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

propensities_cpp <- function(rnet_xptr, v) {
    .Call(`_bondr_propensities_cpp`, rnet_xptr, v)
}

